version: '3'
services:
  wine:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sleep infinity
    volumes:
      - ../:/workspace

  xpra:
    image: hieumai943/xpra:newUpdate
